"""Add created_at to Routine

Revision ID: 87c2d7f74ba1
Revises: 26f5b0e7c745
Create Date: 2025-05-19 19:21:09.858693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87c2d7f74ba1'
down_revision: Union[str, None] = '26f5b0e7c745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routines', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routines', 'created_at')
    # ### end Alembic commands ###
